name: flutter_tindeq
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  go_router: ^7.0.1
  graphic: ^2.2.0
  intl: any
  riverpod_annotation: ^2.1.1
  statistics: ^1.0.25
  soundpool: ^2.3.0
  google_fonts: ^4.0.4
  quick_blue: ^0.3.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  build_runner: ^2.4.4
  riverpod_generator: ^2.2.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  fonts:
    - family: AzeretMono
      fonts:
        - asset: assets/fonts/AzeretMono-Regular.ttf
        - asset: assets/fonts/AzeretMono-Bold.ttf
          weight: 700
    - family: B612Mono
      fonts:
        - asset: assets/fonts/B612Mono-Regular.ttf
        - asset: assets/fonts/B612Mono-Bold.ttf
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
  assets:

    # Add assets from the images directory to the application.
    - assets/images/
    - assets/sound/
